name: Test API Endpoints

on:
  push:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test
        
  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Run endpoint checks
        run: npm run check:endpoints
        env:
          API_KEY: ${{ secrets.TEST_PLANE_TOKEN_API }}
          WORKSPACE_SLUG: ${{ secrets.TEST_PLANE_WORKSPACE_SLUG }}
        
      - name: Run integration tests
        if: success() || failure()  # Run even if previous step fails
        run: npm run test:integration
        env:
          API_KEY: ${{ secrets.TEST_PLANE_TOKEN_API }}
          WORKSPACE_SLUG: ${{ secrets.TEST_PLANE_WORKSPACE_SLUG }}
          
      - name: Create summary report
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "### Unit Tests: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
          echo "### Integration Tests: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "More details in the CI logs." >> $GITHUB_STEP_SUMMARY 